### ISSUE TITLE
[BUG] Multiline, quoted strings are not handled correctly by sdk.ReadObjects

### ISSUE THREAD

**Issue by nieomylnieja** [nobl9/nobl9-go#231]
**Describe the bug**
Double quoted, multiline strings result in an error and are not handled properly by `sdk.ReadObjects` function.

**To Reproduce**

Minimal `main.go`:

```go
package main

import (
	"context"
	"fmt"

	"github.com/nobl9/nobl9-go/manifest"
	"github.com/nobl9/nobl9-go/manifest/v1alpha/project"
	"github.com/nobl9/nobl9-go/sdk"
)

func main() {
	objects, err := sdk.ReadObjects(context.Background(), "./project.yaml")
	if err != nil {
    panic(err)
	}
	fmt.Println(manifest.FilterByKind[project.Project](objects)[0].Spec.Description)
}
```

`project.yaml`:

```yaml
apiVersion: n9/v1alpha
kind: Project
metadata:
    name: test
spec:
  description: "This operation includes the following processes: <br>
- Get all orders in a particular timeframe
"
```

**Expected behavior**

The object should be parsed just fine, the YAML library parses the file just fine on its own, which might hint at quoting handling issues on our side.
Here's a minimal working exmaple:

```go
package main

import (
	"fmt"
	"os"

	"github.com/nobl9/nobl9-go/manifest/v1alpha/project"
  "github.com/goccy/go-yaml"
)

func main() {
	data, err := os.ReadFile("./project.yaml")
	if err != nil {
		panic(err)
	}
	var project project.Project
	if err = yaml.Unmarshal(data, &project); err != nil {
		panic(err)
	}
	fmt.Println(project.Spec.Description)
}
```

**System details (please complete the following information):**
 - Fedora 37
 - 0.77.1
