### ISSUE TITLE
[FEAT] Allow using user email for role binding

### ISSUE THREAD

**Issue by shubhindia** [nobl9/nobl9-go#441]
We are building an internal driver which will allow teams to onboard themselves onto nobl9. Now, as a part of this driver, we need to create some RBAC as well, since each team will have its own project and they'll get access to that particular project only. Same goes for an individual user as well. Now, in case of groups, in our case they will be synced from an enterprise-application in Azure. But for users, all we can do is add that individual user to the enterprise-application. According to the RoleBinding document [here](https://docs.nobl9.com/getting-started/rbac/role-binding-yaml#applying-project-rolebinding) the userID needs to be passed. 
Now, the issue with this is :
1. I could not find any API to get this ID programatically 
2. If the user doesn't already exist, this ID won't be there but we would like to do the roleBinding any ways. 
The workflow is 
 Create Project -> Create an appRoleAssignment (which assigns that user/group to enterprise app) -> Create a roleBinding so that the user/group gets access to the nobl9 project.

**Describe the solution you'd like**
In case of both user and group roleBinding, the input looks like an ID and not the actual username/email or group name. Since, we want to pre-provision the project with all the necessary access already in place, is it possible to create this roleBinding using email or group name (irrespective of if the user already exists or not). 

**Additional context**
For e.g. We have a project called `sloctl-projcet` and `abc@email.com` needs access to it. Now, to grant access, that user should already exist in app.nobl9.com and then we either give access to that user from UI or use a roleBinding. Now, to use roleBinding, we need the userID, which I couldn't find a way to fetch programatically. 
Current Implementation: 
```yaml
apiVersion: n9/v1alpha
kind: RoleBinding
metadata:
  name: 7b565df6-8dd8-4c00-a318-70d82e5043d1
spec:
  projectRef: sloctl-project
  roleRef: project-viewer
  user: 00ucfmbtcr8X9mIcj417

```
Expected Implementation:
```yaml
apiVersion: n9/v1alpha
kind: RoleBinding
metadata:
  name: 7b565df6-8dd8-4c00-a318-70d82e5043d1
spec:
  projectRef: sloctl-project
  roleRef: project-viewer
  user: abc@email.com

``` 
Same goes for groups as well, that way we don't have to wait for users to login and then give them access.
